import type { Metadata } from "next";
import Header from "@/components/public/Header";
import "@/styles/public-globals.css";
import { geistSans, geistMono } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Code The Cure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
