import type { Metadata } from "next";
import Header from "@/components/public/Header";
import "@/styles/globals.css";
import { geistSans, geistMono } from "@/app/ui/fonts";
import { getCurrentUser } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Code The Cure",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = getCurrentUser();

  if (user) {
    redirect("/engine");
  }

  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
